controllers/capitais.py
from flask import render_template, request, redirect, flash, url_for
from utils import db
from models.capitais import Capitais
from flask import Blueprint
from flask_login import login_required, current_user

bp_capitais = Blueprint("capitais", __name__, template_folder='templates')

@bp_capitais.route('/recovery', methods=['POST'])
@login_required
def recovery():
    id_usuario = current_user.id
    try:
        capitais = Capitais.query.filter_by(id_usuario=id_usuario)
        print(capitais[0])
        return render_template('buscar.html', capitais=capitais)
    except:
        return render_template('sem_capitais.html')
    


@bp_capitais.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    if request.method=="GET":
        if current_user.is_authenticated:
	        return render_template('cadastrar_capitais.html')

    if request.method=="POST":
        id_usuario = current_user.id
        regiao = request.form['regiao']
        estado = request.form['estado']
        sigla = request.form['sigla']
        capital = request.form['capital']
        d = Capitais(id_usuario,regiao,estado,sigla,capital)
        db.session.add(d)
        db.session.commit()
        return render_template("buscar.html")

@bp_capitais.route('/update/<id>', methods=['GET', 'POST'])
@login_required
def update(id):
    capital = Capitais.query.filter_by(id=id, id_usuario=current_user.id).first()

    if request.method=="GET":
        return render_template('capital_editar.html', capital=capital)

    if request.method=="POST":
        capital.regiao = request.form['regiao']
        capital.estado = request.form['estado']
        capital.sigla = request.form['sigla']
        capital.capital = request.form['capital']
        db.session.add(capital)
        db.session.commit()
        return render_template('buscar.html')

@bp_capitais.route('/delete/<id>', methods=['GET'])
@login_required
def delete(id):
    capital = Capitais.query.filter_by(id=id, id_usuario=current_user.id).first()
    db.session.delete(capital)
    db.session.commit()
    return render_template('buscar.html')


    

controllers/diario.py
from flask import render_template, request, redirect, flash, url_for
from utils import db
from models.diario import Diario
from flask import Blueprint
from flask_login import login_required, current_user

bp_diario = Blueprint("diario", __name__, template_folder='templates')

@bp_diario.route('/recovery')
@login_required
def recovery():
    id_usuario = current_user.id
    dados = Diario.query.filter_by(id_usuario=id_usuario).all()
    return render_template('diario_recovery.html', dados=dados)

@bp_diario.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    if request.method=="GET":
	    return render_template('diario_create.html')

    if request.method=="POST":
        id_usuario = current_user.id
        titulo = request.form['titulo']
        disciplina = request.form['disciplina']
        d = Diario(id_usuario,titulo,disciplina)
        db.session.add(d)
        db.session.commit()
        return redirect(url_for('diario.recovery'))

@bp_diario.route('/update/<id>', methods=['GET', 'POST'])
@login_required
def update(id):
    d = Diario.query.get(id)

    if request.method=="GET":
        return render_template('diario_update.html', d=d)

    if request.method=="POST":
        d.titulo = request.form['titulo']
        d.disciplina = request.form['disciplina']
        db.session.add(d)
        db.session.commit()
        return redirect(url_for('diario.recovery'))

@bp_diario.route('/delete/<id>', methods=['GET', 'POST'])
@login_required
def delete(id):
    d = Diario.query.get(id)

    if request.method=="GET":
        return render_template('diario_delete.html', d=d)

    if request.method=="POST":
        db.session.delete(d)
        db.session.commit()
        return redirect(url_for('diario.recovery'))


    

controllers/usuario.py
from flask import render_template, request, redirect, flash, url_for
from utils import db, lm
from models.usuario import Usuario
from models.capitais import Capitais
from models.diario import Diario
from flask import Blueprint
from flask_login import login_user, logout_user, current_user, login_required
import hashlib

bp_usuario = Blueprint("usuario", __name__, template_folder='templates')

@login_required
@bp_usuario.route('/')
def home():
    return redirect(url_for('usuario.recovery'))

@login_required
@bp_usuario.route('/recovery')
def recovery():
    dados = Usuario.query.all()
    if current_user.is_authenticated:
        usuario_atual = Usuario.query.filter_by(id=current_user.id).first()
        return render_template('lista_usuarios.html', usuarios=dados, usuario=usuario_atual)
    else:
        try:
            return render_template('lista_usuarios.html', usuarios=dados)
        except:
            return redirect(url_for('login'))

@bp_usuario.route('/create', methods=['GET', 'POST'])
def create():
    if request.method=="GET":
        return render_template('usuario_create.html')

    if request.method=="POST":
        nome = request.form['nome']
        email = request.form['email']
        senha = request.form['senha']

        md5 = hashlib.md5()
        md5.update(senha.encode('utf-8'))
        senha_cripto = md5.hexdigest()

        user = Usuario.query.filter_by(email=email).first()
        if user:
            flash('Email já exsite!', category='error')
            return render_template('usuario_create.html')
        elif len(nome) < 3:
            flash('Nome muito pequeno!', category='error')
            return render_template('usuario_create.html')
        elif len(senha) < 8:
            flash('Senha deve ter no mínimo 8 caracteres', category='error')
            return render_template('usuario_create.html')
        else:
            u = Usuario(nome, email, senha_cripto)
            db.session.add(u)
            db.session.commit()
            login_user(u)
            flash('Conta criada com sucesso!', category='success')
            return redirect(url_for('usuario.recovery'))
      

@lm.user_loader
def load_user(id):
    usuario = Usuario.query.get(id)
    return usuario

@bp_usuario.route('/autenticar', methods=['POST'])
def autenticar():
    email = request.form['email'] 
    senha = request.form['senha']
    usuario = Usuario.query.filter_by(email=email).first()

    md5 = hashlib.md5()
    md5.update(senha.encode('utf-8'))
    senha_cripto = md5.hexdigest()

    if (usuario and usuario.senha == senha_cripto):
        login_user(usuario)
        flash('Logado com suceso!')
        return redirect(url_for('usuario.recovery'))
    else:
        flash('Login ou senha incorretos')
        return redirect('/login')

@bp_usuario.route('/logoff')
def logoff():
    logout_user()
    flash('Usuário desconectado do sistema')
    return redirect('/login')

@bp_usuario.route('/update', methods=['GET', 'POST'])
def update():
    id_usuario = current_user.id
    usuario = Usuario.query.filter_by(id=id_usuario).first()

    if request.method == 'GET':
        return render_template('usuario_update.html', usuario=usuario)
    
    if request.method=="POST":
        nome = request.form['nome']
        email = request.form['email']
        senha = request.form['senha']

        usuario_atual = Usuario.query.filter_by(id=current_user.id).first()
        email_atual = usuario_atual.email

        md5 = hashlib.md5()
        md5.update(senha.encode('utf-8'))
        senha_cripto = md5.hexdigest()

        user = Usuario.query.filter_by(email=email).first()
        if user and user.email != email_atual:
            flash('Email já exsite!', category='error')
            return redirect(url_for('usuario.update'))
        elif len(nome) < 3:
            flash('Nome muito pequeno!', category='error')
            return redirect(url_for('usuario.update'))
        elif senha_cripto != user.senha:
            flash('Senha incorreta!', category='error')
            return redirect(url_for('usuario.update'))
        else:
            user.nome = nome
            user.email = email
            db.session.commit()
            flash('Conta atualizada com sucesso!', category='success')
            return redirect(url_for('usuario.recovery'))
        
@bp_usuario.route('/delete')
def delete():
    if current_user.is_authenticated:
        id = current_user.id
        # logout_user()

        capitais = Capitais.query.filter_by(id_usuario=id).all()
        for capital in capitais:
            db.session.delete(capital)
        db.session.commit()
        

        diarios = Diario.query.filter_by(id_usuario=id).all()
        for diario in diarios:
            db.session.delete(diario)
        db.session.commit()

        usuario = Usuario.query.filter_by(id=id).first()
        db.session.delete(usuario)
        db.session.commit()

        return redirect(url_for('usuario.logoff'))
    

templates/acesso_negado.html
{% extends 'base.html' %}

{% block conteudo %}
    <h2>Você deve fazer o login para acessar essa página.</h2>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Capitais do Brasil</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f0f0f0;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        nav {
            background-color: #007bff;
            width: 100%;
            text-align: center;
            padding: 1rem 0;
            margin-bottom: 1rem;
        }

        nav a {
            color: white;
            text-decoration: none;
            margin: 0 1rem;
            font-size: 1.2rem;
            transition: color 0.3s ease, transform 0.3s ease;
        }

        nav a:hover {
            color: #ffdd57;
            transform: scale(1.1);
        }

        @media (max-width: 600px) {
            nav a {
                display: block;
                margin: 0.5rem 0;
                font-size: 1rem;
            }
        }
        {% block estilo %}

        
        {% endblock %}
    </style>

</head>
<body>
    <nav>
   
    <a href="{{url_for('pagina_inicial')}}">Página Inicial</a> | 
    <a href="{{url_for('capitais.create')}}">Cadastrar Capitais</a> | 
    <a href="{{url_for('fale_conosco')}}">Fale Conosco</a> | 
    {% if current_user.is_authenticated == False %}
    <a href="{{url_for('login')}}">Login</a> | 
    {% endif %}
    <a href="{{url_for('buscar')}}">Buscar</a> 
      
    {% if current_user.is_authenticated %}
    <a href="{{url_for('usuario.logoff')}}" class="btn btn-primary">Sair ({{current_user.nome}})</a>
    {% endif %}
    
    </nav>

    <main>
        {% block conteudo %}
        {% endblock %}
    </main>

</body>
</html>
<!-- fazer -->
<!-- um html com formulário de cadastro das capitais -->
 <!-- e outra html com tabela listando as capitais cadastradas -->

templates/buscar.html
{% extends "base.html" %}

{% block estilo %}

    
    body {
       font-family: Arial, sans-serif;
       display: flex;
       justify-content: center;
       align-items: center;
       height: 100vh;
       margin: 0;
   }
   
   .container {
       text-align: center;
   }
   
   .btn-principal {
       background-color: #007bff;
       color: white;
       border: none;
       padding: 10px 20px;
       font-size: 16px;
       cursor: pointer;
       margin-bottom: 10px;
   }
   
   .btn-secundario {
       background-color: yellow;
       color: black;
       border: 1px solid black;
       padding: 10px 20px;
       font-size: 16px;
       cursor: pointer;
       margin-bottom: 20px;
       display: block;
       margin: 10px auto;
   }
   
   table {
       width: 100%;
       border-collapse: collapse;
   }
   
   th, td {
       border: 1px solid black;
       padding: 10px;
       text-align: center;
   }
   
   thead {
       background-color: #f2f2f2;
   }
   
   .btn-editar, .btn-apagar {
       background-color: white;
       border: 1px solid black;
       padding: 5px 10px;
       cursor: pointer;
   }
   
   .btn-editar:hover {
       background-color: #e7e7e7;
   }
   
   .btn-apagar:hover {
       background-color: #f2f2f2;
   }
   
{% endblock %}


{% block conteudo %}

    <div class="container">
        <h2>BUSCAR AS CAPITAIS DO BRASIL</h2>

        <form action="{{ url_for('capitais.recovery') }}" method="post">
            <button class="btn-secundario">BUSCAR</button>
        </form>
        
        {% if capitais is defined  %}
        <table>
            <thead>
                <tr>
                    <th>Estado</th>
                    <th>Sigla</th>
                    <th>Capital</th>
                </tr>
            </thead>
            <tbody>
                {% for capital in capitais %}
                <tr>
                    <td>{{ capital.estado }}</td>
                    <td>{{ capital.sigla }}</td>
                    <td>{{ capital.capital }}</td>
                    <td>
                        <form action="{{url_for('capitais.update', id=capital.id)}}" method="get">
                            <button class="btn-editar">EDITAR</button>
                        </form>
                    </td>
                    <td>
                        <button onclick="confirmarEApagar({{capital.id}})" class="btn-apagar">APAGAR</button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <script>
            function confirmarEApagar(id){
                if (confirm('Você tem certeza de que deseja apagar esta capital?')) {
                    window.location.href = "{{ url_for('capitais.delete', id='') }}"+id;
                } else {
                    alert('Ação cancelada.')
                }
            }
        </script>
        {% endif %}
    </div>

{% endblock %}

templates/cadastrar_capitais.html
{% extends "base.html" %}

{% block estilo %}

    body {
    font-family: Arial, sans-serif;
    background-color: #f0f0f0;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    margin: 0;
}

.form-container {
    background-color: #fff;
    padding: 20px;
    border-radius: 8px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    width: 300px;
    text-align: center;
}

h2 {
    margin-bottom: 20px;
}

label {
    display: block;
    margin-bottom: 5px;
    text-align: left;
}

input, select {
    width: 100%;
    padding: 10px;
    margin-bottom: 15px;
    border: 1px solid #ccc;
    border-radius: 4px;
}

button {
    width: 100%;
    padding: 10px;
    background-color: #007BFF;
    color: #fff;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    font-size: 16px;
}

button:hover {
    background-color: #0056b3;
}

{% endblock%}

{% block conteudo %}

    <div class="form-container">
        <h2>Cadastro das Regiões, Estados e Capitais do Brasil</h2>
        <form action="{{ url_for('capitais.create') }}" method="post">
            <label for="regiao">Região:</label>
            <select id="regiao" name="regiao" required>
                <option value="">Selecione a região</option>
                <option value="norte">Norte</option>
                <option value="nordeste">Nordeste</option>
                <option value="centro-oeste">Centro-Oeste</option>
                <option value="sudeste">Sudeste</option>
                <option value="sul">Sul</option>
            </select>
            <label for="estado">Estado:</label>
            <input type="text" id="estado" name="estado" required>

            <label for="sigla">Sigla:</label>
            <input type="text" id="sigla" name="sigla" required>

            <label for="capital">Capital:</label>
            <input type="text" id="capital" name="capital" required>    
            
            <hr>
            <a href="{{ url_for('pagina_inicial') }}">Voltar</a>

            <button type="submit">Cadastrar</button>
        </form>
    </div>



{% endblock %}

templates/diario_create.html
{% extends 'base.html' %}
{% block conteudo %}

<!-- <form action="/diario/create" method="POST"> -->
<form action="{{url_for('diario.create')}}" method="POST">
  Titulo: <input type="text" name="titulo"><br/>
  Disciplina: <input type="text" name="disciplina"><br/>
  <input type="submit" name="Cadastrar">
  <input type="reset" name="Limpar">
</form>

{% endblock %}

templates/diario_delete.html
{% extends 'base.html' %}
{% block conteudo %}

<form action="{{url_for('diario.delete', id=d.id)}}" method="POST">
  Você realmente deseja excluir a disciplina {{d.disciplina}}?
  <input type="submit" name="Sim">
</form>
<a href="{{url_for('diario.recovery')}}">Cancelar</a>

{% endblock %}

templates/diario_recovery.html
{% extends 'base.html' %}
{% block conteudo %}

    <p>
        <button><a href="{{url_for('diario.create', id=id)}}">Novo diário</a></button>
    </p>
    <ul>

    {% for d in dados %}
        <li>
            {{d.titulo}} - {{d.disciplina}} -
            <a href="{{url_for('diario.update', id=d.id)}}">editar</a>
            <a href="{{url_for('diario.delete', id=d.id)}}">excluir</a>
            
        </li>
    {% endfor %}
	</ul>
{% endblock %}

templates/diario_update.html
{% extends 'base.html' %}
{% block conteudo %}

<!-- <form action="/diario/update" method="POST">-->
<form action="{{url_for('diario.update', id=d.id)}}" method="POST">
  Titulo: <input type="text" name="titulo" value="{{d.titulo}}"><br/>
  Disciplina: <input type="text" name="disciplina" value="{{d.disciplina}}"><br/>
  <input type="submit" name="Cadastrar">
  <input type="reset" name="Limpar">
</form>

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block estilo %}


body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    background-color: #f0f0f0;
}

h1 {
    color: #333;
    font-size: 2rem;
    text-align: center;
    margin: 1rem 0;
    transition: font-size 0.3s ease, color 0.3s ease;
}

@media (min-width: 768px) {
    h1 {
        font-size: 3rem;
        color: #007bff;
    }
}

h1:hover {
    color: #0056b3;
}


{% endblock%}

{% block conteudo %}

    <h1>Bem-vindo à Nossa Página das Capitais do Brasil</h1>

    <!-- colocar a imagem do mapa do Brasil com todas as capitais aqui! -->
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block estilo %}

  body {
    font-family: Arial, sans-serif;
    background-color: #f0f0f0;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    margin: 0;
}

.login-container {
    background-color: #fff;
    padding: 30px 20px;
    border-radius: 8px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    width: 300px;
    text-align: center;
}

h2 {
    margin-bottom: 20px;
    color: #333;
    position: relative;
}

h2::after {
    content: '';
    display: block;
    width: 50px;
    height: 3px;
    background-color: #f04e23;
    position: absolute;
    bottom: -10px;
    left: 50%;
    transform: translateX(-50%);
}

label {
    display: block;
    margin-bottom: 5px;
    text-align: left;
    font-size: 14px;
    color: #333;
}

input[type="email"],
input[type="password"] {
    width: 100%;
    padding: 10px;
    margin-bottom: 15px;
    border: 1px solid #ccc;
    border-radius: 4px;
    font-size: 14px;
}

.remember-me {
    display: flex;
    align-items: center;
    margin-bottom: 20px;
}

.remember-me input {
    margin-right: 10px;
}

button {
    width: 100%;
    padding: 10px;
    background-color: #007BFF;
    color: #fff;
    border: none;
    border-radius: 25px;
    cursor: pointer;
    font-size: 16px;
}

button:hover {
    background-color: #0056b3;
}

.forgot-password {
    margin-top: 10px;
}

.forgot-password a {
    text-decoration: none;
    font-size: 14px;
    color: #666;
}

.forgot-password a span {
    color: #007BFF;
    text-decoration: underline;
}

.forgot-password a:hover span {
    color: #0056b3;
}


{% endblock%}

{% block conteudo %}

{% with messages = get_flashed_messages() %}
    {% for message in messages %}
        <script>alert('{{message}}')</script>
    {% endfor %}
{% endwith %}

<body>
  <div class="login-container">
    <form action="{{url_for('usuario.autenticar')}}" method="post"> 
      <h2>Faça o seu login</h2>
      <form>
          <label for="email">Seu e-mail*</label>
          <input type="email" id="email" name="email" required>

          <label for="senha">Sua senha*</label>
          <input type="password" id="senha" name="senha" required>

          <div class="remember-me">
              <input type="checkbox" id="lembrar-me" name="lembrar-me">
              <label for="lembrar-me">Lembrar-me</label>
          </div>

          <button type="submit">ENTRAR</button>
          
          <div class="forgot-password">
            <p>
            Não tem cadastro? Registre-se <a href="{{url_for('usuario.create')}}">aqui</a>
            </p>
          </div>
      </form>
  </div>
</body>

{% endblock %}

templates/not_found.html
{% extends 'base.html' %}

{% block conteudo %}
    <h2>Página não encontrada</h2>
{% endblock %}

templates/pagina_inicial.html
{% extends "base.html" %}

{% block estilo %}

    body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    background-color: #f0f0f0;
    display: flex;
    flex-direction: column;
    align-items: center;
}

header {
    background-color: #4caf50;
    color: white;
    padding: 1rem;
    width: 100%;
    text-align: center;
}

nav {
    background-color: #007bff;
    width: 100%;
    text-align: center;
    padding: 1rem 0;
    margin-bottom: 1rem;
}

nav a {
    color: white;
    text-decoration: none;
    margin: 0 1rem;
    font-size: 1.2rem;
    transition: color 0.3s ease, transform 0.3s ease;
}

nav a:hover {
    color: #ffdd57;
    transform: scale(1.1);
}

@media (max-width: 600px) {
    nav a {
        display: block;
        margin: 0.5rem 0;
        font-size: 1rem;
    }
}

main {
    max-width: 800px;
    width: 100%;
    padding: 1rem;
    background-color: white;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    margin-bottom: 1rem;
}

section {
    margin-bottom: 1.5rem;
}

h2 {
    color: #333;
    margin-bottom: 0.5rem;
}

p {
    color: black;
    line-height: 1.6;
}

footer {
    background-color: #4caf50;
    color: white;
    padding: 0.5rem;
    width: 100%;
    text-align: center;
}


{% endblock %}

{% block conteudo %}

<body>
    <header>
        <h1>Bem-vindo ao Brasil</h1>
    </header>
        <main>
        <section>
            <h2>Sobre o Brasil</h2>
            <p>O Brasil é um país vasto e diversificado, localizado na América do Sul. É dividido em cinco regiões: Norte, Nordeste, Centro-Oeste, Sudeste e Sul. Cada região é composta por vários estados, e cada estado tem sua capital. Ao todo, o Brasil possui 26 estados e um Distrito Federal, onde está localizada a capital do país, Brasília.</p>
        </section>
    </main>
    <footer>
        <p>Capitais do Brasil. Todos os direitos reservados.</p>
    </footer>
</body>


{% endblock %}

templates/sem_capitais.html
{% extends "base.html" %}
{% block conteudo %}
<h2>Você não cadastrou capitais! Para cadastrar capitais, aperte <a href="{{ url_for('cadastrar_capitais') }}">aqui</a></h2>
{% endblock %}

templates/usuario_create.html
{% extends 'base.html' %}

{% block conteudo %}
    <form action="{{url_for('usuario.create')}}" method="post">
    Nome: <input type="text" name="nome"><br/>
    E-mail: <input type="email" name="email"><br/>
    Senha: <input type="text" name="senha"><br/>
    Confirmar senha: <input type="text" name="csenha"><br/>
    <input type="submit" value="Cadastrar">
    <input type="reset" value="Limpar">
    </form>
{% endblock %}